before:
  hooks:
    - go mod download

builds:
  - id: echo
    main: external-plugins/executors/echo/main.go
    binary: executor_echo_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: &env
      - CGO_ENABLED=0
    goos: &goos
      - linux
    goarch: &goarch
      - amd64
    goarm: &goarm
      - 7

  - id: tracker
    main: external-plugins/sources/tracker/main.go
    binary: source_tracker_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

  - id: auth
    main: external-plugins/executors/auth/main.go
    binary: source_ticker_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

snapshot:
  name_template: 'v1.0'


release:
  # If set to true, will not auto-publish the release.
  draft: false
  prerelease: auto

  # Add extra pre-existing files to the release.
  # - build plugin index.yaml
  extra_files:
    - glob: ./plugins-index.yaml